---
dist: trusty
sudo: required
language:
  - cpp
  - pyhton
compiler:
  - gcc
python:
  - "2.7"
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"

cache:
  directories:
    - "~/.platformio"

install:
  - pip install --user platformio

script:
  - make ci

